### ISSUE TITLE
File dialog with no prompt when creating widget - Linux Mint

### ISSUE THREAD

**Issue by koas** [Glitter/Glitter#7]
I'm trying to create a widget, and after filling the title, subtitle, width and height I click the "Create the widget" button. A file dialog with no title or prompt pops up, and I don't know why.

Is it for loading an icon for the widget? Or maybe I should select a folder where the widget code will be saved? I suppose it's the latter, but it's not clear.

I think the file dialog should have a title indicating what are we supposed to select, or maybe add a little text in the create widget form like "In the next step you will be prompted to select where Glitter will store your widget files".

Attached is the screenshot of the file dialog. OS is Linux Mint 18.3 Cinnamon 64 bit. Cinnamon version is 3.6.7.

![screenshot](https://user-images.githubusercontent.com/3851754/72787705-b7ebc480-3c30-11ea-8bf7-af995acb8d8a.png)

**Comment by OriginalEXE** [comment]
Hello, thank you for reporting this. The dialog in question is used to select a directory where you want to store the files of the widget that you are creating. I agree more context would definitely help out. Of course, it's obvious to me because I made it, but this is exactly why other people testing it is so valuable.

Thanks again for trying out Glitter, appreciated. I will keep you updated here. I am on a business trip for the next few days, but you can expect some progress this week.

**Comment by OriginalEXE** [comment]
What do you think about something like this?

I added the info message and changed the button text to more closely describe what will actually happen.

![save-widget-context](https://user-images.githubusercontent.com/2056251/73016990-40c85300-3e1f-11ea-91d1-7512f918bb4d.png)

**Comment by koas** [comment]
I think that makes it very clear, thanks!
